accept multiple forms for getMostRecentReport
medic/cht-nootils pull request #23
Opened 2021-09-20 16:32 UTC by freddieptf

2021-09-21 01:56 UTC, kennsippell requested changes

2021-09-21 01:56 UTC, kennsippell commented on src/nootils.js
> +      if (!Array.isArray(forms)) throw 'expecting forms to be a string array';
as we discussed today - this needs to be backward compatible

2021-09-21 07:30 UTC, dianabarsan requested changes
Nice work! I just have a couple of suggestions in line.

2021-09-21 07:30 UTC, dianabarsan commented on src/nootils.js
> +      if (!Array.isArray(forms)) return lib.getMostRecentReport(reports, [forms], fields);
A cleaner way to do this, that doesn't require recursion, and is safer from this point of view, is to do: 
```suggestion
      if (!Array.isArray(forms)) {
        forms = [forms];
      }
```

2021-09-21 07:30 UTC, dianabarsan commented on test/nootils.spec.js
> +        { _id: 4, form: 'H', reported_date: 4 }
To improve functional coverage, please add some reports that don't match the forms, so we make sure those are not returned as results. Also, please shuffle `reports` so we don't pass an ordered list. 
Something like: 
```
    const reports = [
        { _id: 6, form: 'B', reported_date: 9 },
        { _id: 3, form: 'V', reported_date: 3 },
        { _id: 4, form: 'H', reported_date: 4 },
        { _id: 2, form: 'V', reported_date: 2 },
        { _id: 5, form: 'A', reported_date: 6 },
        { _id: 1, form: 'H', reported_date: 1 },
        { _id: 7, form: 'C', reported_date: 12 },
      ];
```

2021-09-21 11:44 UTC, dianabarsan approved these changes
Nice work, thanks for taking this on! 

I think we're running into some technical difficulties before this code becomes usable in production: 
1. Travis CI isn't running for the PR, so this can't be merged even if approved. We should migrate to using GHA and update the requirements. 
2. We need to release a new version of cht-nootils and bump the dependency in cht-core for this code to be in effect: https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/rules-emitter.js#L9

2021-09-21 19:04 UTC, dianabarsan commented
Can you please try rebasing off of master to get the new CI setup, please?

2021-09-21 19:15 UTC, freddieptf commented
Done

2021-09-27 19:44 UTC, kennsippell approved these changes

2021-10-06 02:21 UTC, merged